### ISSUE TITLE
A revolt server?

### ISSUE THREAD

**Issue by MCausc78** [siren15/Pyre#1]
Hello. Recently I was curious and wanted to find other Python libraries for Revolt (apart from my [own](https://github.com/MCausc78/pyvolt)). Wanted to ask, is there a Revolt server about Pyre?

A few recommendations:
- If you aim at performance, be aware that [`enum.Enum`](https://github.com/Rapptz/discord.py/commit/991140eebe4a618354ada9ec592e9a405dab604d) is extremely slow. You could consider using discord.py's Enum instead.
- You might want try [msgspec](https://github.com/jcrist/msgspec), since people say it faster than pydantic (and their README provides benchmarks). However, it does not work on PyPy due to CPython internals usage (for performance reasons).
- Try avoiding validating payloads sent by backend (https://github.com/siren15/Pyre/blob/5d8c424540cc1ad2b799e2a551e901816f2ad6f5/pyre/utils.py#L7-L23). RegExp might slow down your deserialization processes. Chances that payloads are valid are high.
- A lot of `bool`'s in Revolt models are not present if [their value is false](https://github.com/revoltchat/backend/blob/475fa6f2e6b59c3ef5d674aa6493b1e68ae460fa/crates/core/models/src/v0/servers.rs#L63-L80). You probably don't want library users to do [unnecessary type narrowing](https://github.com/siren15/Pyre/blob/5d8c424540cc1ad2b799e2a551e901816f2ad6f5/pyre/models/server.py#L31).
- Having a big [member's list](https://github.com/siren15/Pyre/blob/5d8c424540cc1ad2b799e2a551e901816f2ad6f5/pyre/cache.py#L69-L73) is generally not good idea and often makes poor performance when there is lot of members (common for user accounts). I use `Dict[str, Dict[str, Member]]`.

**Comment by siren15** [comment]
A month later, but here's some answers anyways. 

There is technically a server, but since I'm not actually working on this as my main project as my time is scarce, I'm not gonna promote it as it would be hard for me to even check it at this time. If people need to contact me about this project, github is always here.

Plus this is a WIP and will stay so for a much longer like it is. I don't have as much time to work on this as I would like to. Is it technically usable? Sure. But I don't recommend it being the main library someone would want to use, it's still very much bare. Plus I ain't really giving support because of that. After all my intention for this was to learn myself more about APIs and wrappers and how to build them. Something coming off of this project or people wanting to use it is a welcome thing, but not expected.

I'm not really concerned about performance with either enums or custom validations, as custom validations are there to validate user input, not the server input. And as I want to make my life easy, I want to reuse as much of my models as I can.

I'm not concerned about pydantic, I have experience using it and I haven't really seen much of issues with large datasets. And since my library is focusing on being model centric(and I want users to define the types of the vars), I would need to scrap everything to start with something new and I ain't doing that.

I don't really want to remove the ability of users having all the members, it's something even I personally use for my Discord bots. It's a function to call, it's not degrading performance by being there. And if I notice the function being very slow itself, I can always find a better way of doing it.
